name: cdo_test1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  window_size: ^0.1.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

  # Package added for beautiful list animations
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
   android: true
   ios: true
   image_path: "assets/header-logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - lib/logos/header-logo.jpg
    - lib/logos/logo-qualiopi-2022.png
    - lib/logos/26_ind.jpg
    - lib/logos/21_ind.jpg
    - lib/logos/24_ind.jpg
    - assets/header-logo.jpg
    - lib/logos/image55.png
    - lib/logos/reunion.jpg
    - assets/form1.jpeg
    - assets/form2.jpeg
    - assets/form3.jpeg
    - assets/form4.jpeg
    - assets/form5.jpeg
    

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700